name: Convert Markdown naar HTML

on:
  push:
    branches: [web, main]
    paths:
      - 'docs/**/*.md'
  
jobs:
  build:
    runs-on: [self-hosted, Linux, X64, mko-docker]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc file

      - name: Convert Markdown naar HTML
        run: |
          for file in $(find docs -name "*.md"); do
            encoding=$(file -bi "$file")

            if [[ $encoding == *"utf-16"* ]]; then
              iconv -f utf-16 -t utf-8 "$file" > "${file}.utf8"
              pandoc "${file}.utf8" -o "${file%.md}.html"
            else
              pandoc "$file" -o "${file%.md}.html"
            fi
          done


      - name: Commit HTML
        run: |
          git config --global user.name "${{ runner.name }}"
          git config --global user.email "actions@github.com"
          git add 'docs/**/*.html'
          git diff --cached --quiet || git commit -m "Auto-convert Markdown to HTML"
          git push